# source "https://rubygems.org"

# group :jekyll_plugins do
#   gem "jekyll-bookshop", "2.2.2"
#   gem "cloudcannon-jekyll-bookshop", "2.2.2"
#   gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
#   gem 'jekyll-tagging'
#   gem "jekyll-sitemap"
#   gem "jekyll-pagebreak", "~> 0.9.2"
# end

# gem "webrick", "~> 1.8"
# 22
# source "https://rubygems.org"
# gem 'jekyll', '~> 4.2'

# group :jekyll_plugins do
#   gem "jekyll-bookshop", "2.2.2"
#   gem "cloudcannon-jekyll-bookshop", "2.2.2"
#   gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
#   gem 'jekyll-tagging'
#   gem "jekyll-sitemap"
#   gem "jekyll-pagebreak", "~> 0.9.2"
# end
# source "https://rubygems.org"
source "https://rubygems.org"
gem 'jekyll', '~> 4.2'
group :jekyll_plugins do
  gem "jekyll-bookshop", "3.6.2"
  gem "cloudcannon-jekyll-bookshop", "3.3.0"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-tagging'
  gem "jekyll-sitemap"
  gem "jekyll-pagebreak"
end
