# source "https://rubygems.org"

# group :jekyll_plugins do
#   gem "jekyll-bookshop", "2.2.2"
#   gem "cloudcannon-jekyll-bookshop", "2.2.2"
#   gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
#   gem 'jekyll-tagging'
#   gem "jekyll-sitemap"
#   gem "jekyll-pagebreak", "~> 0.9.2"
# end

# gem "webrick", "~> 1.8"
# 22
# source "https://rubygems.org"
# gem 'jekyll', '~> 4.2'

# group :jekyll_plugins do
#   gem "jekyll-bookshop", "2.2.2"
#   gem "cloudcannon-jekyll-bookshop", "2.2.2"
#   gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
#   gem 'jekyll-tagging'
#   gem "jekyll-sitemap"
#   gem "jekyll-pagebreak", "~> 0.9.2"
# end
# source "https://rubygems.org"
source "https://rubygems.org"
# gem 'jekyll', '~> 4.3.2'
gem 'sass'
gem 'sass-embedded', '~> 1.55'
group :jekyll_plugins do
  gem "jekyll-bookshop", "2.2.2"
  gem "cloudcannon-jekyll-bookshop", "2.2.2"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-tagging'
  gem "jekyll-sitemap"
  gem "jekyll-pagebreak"
  gem 'jekyll-sass-converter', :git => "https://github.com/CloudCannon/jekyll-sass-converter.git"
  gem 'jekyll-postcss-v2'
  gem 'jekyll-archives', '~> 2.2.1'
  gem 'jekyll-feed', '~> 0.15.1'

end
